### PR TITLE
Fix/docs requirement installation

### PR DESCRIPTION
**Pull request by MaGering**
This PR fixes the installation of the docs by 

1. moving `docs_requirements.txt` back into `docs` directory and
2. replacing the old structure uninstalling from `setup.py` with installing using poetry from `pyproject.toml`.

The `README.md` has been updated accordingly.

### CODE REVIEW

**Comment by MaGering** [comment]
I've tested it locally. There it works. Now I activated the branch to trigger a build at `Read the docs`:

https://readthedocs.org/projects/oemof-b3/builds/16242353/

**Review by jnnr — CHANGES_REQUESTED** [review]
Thanks for fixing this. The docs are built, but the script headers are not rendered. Need to check the logs in rtd.

**Comment by MaGering** [comment]
_Conclusion:_
Dependencies aren't installed when adding `pyproject.toml` to `docs_requirements.txt`. A solution is needed to trigger the installation of the poetry dependencies from the `docs_requirements.txt`.

Another problem occurs when adding `demandlib` to poetry dependencies. It needs `pandas = ">=1.0.0"` but `pandas = "0.25.3"` is installed. That is why the checks fail now. We need a solution for this as well. Modifying `pandas = "0.25.3"` to `pandas = ">=1.0.0"` in `pyproject.toml` led me to:

```
Because oemof-b3 depends on pandas (>=1.0.0) which doesn't match any versions, version solving failed.
```

**Comment by henhuy** [comment]
Added doc requirements to poetry as `extras`. Updated `.readthedocs.yml` to install all dependencies from poetry together with docs deps. Please check if RTD looks good now!

As for demandlib - this has to wait for #167

**Comment by henhuy** [comment]
Please wait with check - have to fix something first. sorry

**Comment by jnnr** [comment]
Already checked - rtds fails: `WARNING: unknown 0.0.0 does not provide the extra 'docs'`

**Comment by henhuy** [comment]
> Already checked - rtds fails: `WARNING: unknown 0.0.0 does not provide the extra 'docs'`

yes - had the same error. Now it should work!

**Comment by henhuy** [comment]
Split RTD dep installaiton into two parts:
- installation of doc requirements from `docs_requirements.txt` file and
- Oemof-B3 installation from pip using poetry.
Build process completes.

Nevertheless, this should be possible with poetry as well - don't know why it fails. Wrote a comment here: https://github.com/python-poetry/poetry/issues/3348#issuecomment-1057935868

**Comment by MaGering** [comment]
Even if the build is successful with your latest commit @henhuy, there is also the problem, that I wanted to mention here, of ignored `autodoc` in `model pipeline` on [this branch](https://readthedocs.org/projects/oemof-b3/builds/16254667/) :

```
/home/docs/checkouts/readthedocs.org/user_builds/oemof-b3/checkouts/fix-docs_requirement_installation/docs/model_structure.rst:5: WARNING: Duplicate explicit target name: "oemoflex".
WARNING: autodoc: failed to import module 'optimize'; the following exception was raised:
No module named 'oemof'
WARNING: autodoc: failed to import module 'plot_dispatch'; the following exception was raised:
No module named 'pandas'
WARNING: autodoc: failed to import module 'plot_conv_pp'; the following exception was raised:
No module named 'plot_conv_pp'
WARNING: autodoc: failed to import module 'join_scenarios'; the following exception was raised:
No module named 'pandas'
WARNING: autodoc: failed to import module 'postprocess'; the following exception was raised:
No module named 'oemof'
WARNING: autodoc: failed to import module 'build_datapackage'; the following exception was raised:
No module named 'pandas'
WARNING: autodoc: failed to import module 'prepare_conv_pp'; the following exception was raised:
No module named 'pandas'
WARNING: autodoc: failed to import module 'prepare_electricity_demand'; the following exception was raised:
No module named 'pandas'
WARNING: autodoc: failed to import module 'prepare_feedin'; the following exception was raised:
No module named 'pandas'
WARNING: autodoc: failed to import module 'prepare_heat_demand'; the following exception was raised:
No module named 'numpy'
WARNING: autodoc: failed to import module 'prepare_re_potential'; the following exception was raised:
No module named 'pandas'
WARNING: autodoc: failed to import module 'process_re_potential'; the following exception was raised:
No module named 'pandas'
```
While it applied for `plot_conv_pp`, `geopandas` and `demandlib` only on [the last successfully built dev branch](https://readthedocs.org/projects/oemof-b3/builds/16232728/):

```
/home/docs/checkouts/readthedocs.org/user_builds/oemof-b3/checkouts/latest/docs/model_structure.rst:5: WARNING: Duplicate explicit target name: "oemoflex".
WARNING: autodoc: failed to import module 'plot_conv_pp'; the following exception was raised:
No module named 'plot_conv_pp'
WARNING: autodoc: failed to import module 'prepare_conv_pp'; the following exception was raised:
No module named 'geopandas'. You need to install 'geopandas' in order to use this script.
WARNING: autodoc: failed to import module 'prepare_heat_demand'; the following exception was raised:
No module named 'demand
```
as you can see above installation of `oemof`, `numpy` and `pandas` seams to be a problem now as well. Any idea why?

**Comment by henhuy** [comment]
Now all modules are mocked instead of installing all dependencies. (deps not needed for autodoc)
Nice side-effect: RTD builds a lot faster!

**Review by jnnr — APPROVED** [review]
Thanks for fixing this!

**Pull request merged**
