### PR TITLE
Implement github actions 

### LINKED ISSUE #6: [Ci] Travis not set up

### PR DESCRIPTION
**Pull request by SabineHaas**
Fix #6 

Changes proposed in this PR:
- Add github actions workflow including: 
     - run tests with pytest
     - add test coverage
     - check linting with black
- Remove `test_requirements.txt` and add `extras_require` to `setup.py`

The checks are done for python 3.7 and 3.8 currently, this can be adapted of course.

### CODE REVIEW

**Comment by SabineHaas** [comment]
@jnnr and @juliusmeier you can lint your code with Black (run `black . --exclude docs/`). The CI will remind you to do so, as the build will fail if the code is not linted with black, as soon as #25 is merged.

You can install the extra requirements with dev option via  `pip install -e .[dev]` assuming you navigated to the directory where `setup.py` is located.

@jnnr this PR should be merged soon to prevent merge conflicts due to the code linting.

**Comment by jnnr** [comment]
> @jnnr and @juliusmeier you can lint your code with Black (run `black . --exclude docs/`). The CI will remind you to do so, as the build will fail if the code is not linted with black, as soon as #25 is merged.

How do you do it? Do you have black added to your pre-commit hook?

**Comment by jnnr** [comment]
Shall we use flake8 as well? I am for it.

**Comment by SabineHaas** [comment]
> > @jnnr and @juliusmeier you can lint your code with Black (run `black . --exclude docs/`). The CI will remind you to do so, as the build will fail if the code is not linted with black, as soon as #25 is merged.
> 
> How do you do it? Do you have black added to your pre-commit hook? **update**: Did so and am happy with it.

nice :+1: could you post here, how you did that? 

If you've followed instructions from your above posted [link](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/) I understand that this can be added to the repo, so that it is a setting for all of us..?!


> Shall we use flake8 as well? I am for it. To prevent conflicts with black, some rules should be ignored. I found information [here] (https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/) and in this recent oemof-solph PR [oemof/oemof-solph#746](https://github.com/oemof/oemof-solph/pull/746).

Ah yes, I can add this.

**Comment by jnnr** [comment]
> > How do you do it? Do you have black added to your pre-commit hook? **update**: Did so and am happy with it.
> 
> nice +1 could you post here, how you did that?

I added a file named pre-commit (no extension) to my local git repo's .git/hooks. The file contains:

```
#!/bin/sh
flake8 .
black . --exclude /docs
```

Maybe the order matters?

Then, I made the file executable by chmod +x <file>

Now, each time when I commit, the linters run first and stop the commit if there is mistake.

**Comment by SabineHaas** [comment]
> > > How do you do it? Do you have black added to your pre-commit hook? **update**: Did so and am happy with it.
> > 
> > 
> > nice +1 could you post here, how you did that?
> 
> I added a file named pre-commit (no extension) to my local git repo's .git/hooks. The file contains:
> 
> ```
> #!/bin/sh
> flake8 .
> black . --exclude /docs
> ```
> 
> Maybe the order matters?
> 
> Then, I made the file executable by chmod +x
> 
> Now, each time when I commit, the linters run first and stop the commit if there is mistake.

Nice thank you! I guess you could even push that to the repo, so that we can use it, as well.

Now you can use `black .`, no need for `--exclude`, as I've added a config file for black, too.

**Review by jnnr — APPROVED** [review]

**Pull request merged**
