### PR TITLE
Update example scenario documentation

### PR DESCRIPTION
**Pull request by jnnr**
This PR renames the example scenarios in the docs and adds some more text.

TODO
* [x] Update the capacities to match the current version of NEP in the link (done in https://github.com/rl-institut/oemof-B3/pull/11)
* [x] Create a proper citation of the NEP document stating the version of the draft and an access date.

### CODE REVIEW

**Comment by jnnr** [comment]
Thanks for 9f12b6a, @juliusmeier! Unfortunately, I get an error. sphinxcontrib-bibtex does not seem to recognize the item type "online". I tried to change it to "report", but got the same result.

**Comment by juliusmeier** [comment]
> Unfortunately, I get an error. sphinxcontrib-bibtex does not seem to recognize the item type "online". I tried to change it to "report", but got the same result.

On my computer, it works. But I will have a look.

**Comment by jnnr** [comment]
Thanks for updating. Now it works for me as well. But the citation itself does not look

**Comment by jnnr** [comment]
> Thanks for updating. Now it works for me as well.
> 
> The citation itself does not look proper yet. The license (CC-BY 4.0) seems misplaced. Maybe you can even drop the author (Übertragungsnetzbetreiber).

Seems like this is the way the document is supposed to be cited. In that case, this is ready to be merged, right? @juliusmeier

**Comment by juliusmeier** [comment]
> Seems like this is the way the document is supposed to be cited. In that case, this is ready to be merged, right? @juliusmeier

Yes, I merge it.

**Comment by jnnr** [comment]
From my side, this seems finished and ready to merge. Any objections, @juliusmeier?

**Comment by juliusmeier** [comment]
> From my side, this seems finished and ready to merge. Any objections, @juliusmeier?

No, can be merged. I will do it now.

**Pull request merged**
