### PR TITLE
Unify resource names

### PR DESCRIPTION
**Pull request by jnnr**
This PR unifies the names of the resources according to the convention:

`ts/scal_<general_description>_<details>.csv`

I did not change `prepare_re_potential` because I do not know if I this applies to all files in `RE_potential`. Can you give your feedback @SabineHaas?

### CODE REVIEW

**Comment by SabineHaas** [comment]
> I did not change `prepare_re_potential` because I do not know if I this applies to all files in `RE_potential`.

Yes I think it's fine like that, as files in `RE_potential` are no resources to the model but intermediate outcome.

**Review by SabineHaas — COMMENTED** [review]
Should rule `prepare_scalars` already work? I get:
```
  File "scripts/prepare_scalars.py", line 76, in annuise_investment_cost
    assert isinstance(wacc, float)
AssertionError
```

Everything else looks good!

**Comment by jnnr** [comment]
> Should rule `prepare_scalars` already work? I get:
> 
> ```
>   File "scripts/prepare_scalars.py", line 76, in annuise_investment_cost
>     assert isinstance(wacc, float)
> AssertionError
> ```

I fixed this in a commit on another branch. Cherry-picked it here to fix the problem.

**Comment by jnnr** [comment]
The fix of `load_b3_scalars` occurred to be more complicated. I fixed this here even if I later realised that a separate branch would have been appropriate.

**Pull request merged**
