### PR TITLE
Fix by adapting output path handling

### LINKED ISSUE #303: Rule plot_all_resources stopped working
Probably because the COLORS dictionary has changed (the keys are mapped to German/English) to match the labels.

### PR DESCRIPTION
**Pull request by MaGering**
Resolves #303

The file type is added twice to the file name and hence the output can never be build by snakemake. With this commit the file path is set according to the file type in the settings.

This PR fixes the issue. Is only working with changes in PR https://github.com/rl-institut/oemof-B3/pull/336.

### CODE REVIEW

**Comment by MaGering** [comment]
Again checks not working due to problem described in my comment [here](https://github.com/rl-institut/oemof-B3/pull/336#issuecomment-1697162784). Hence this PR should be merged after https://github.com/rl-institut/oemof-B3/pull/336.

**Comment by MaGering** [comment]
Ready for your review @Stefanie08!

You need the changes in PR https://github.com/rl-institut/oemof-B3/pull/336 for your review. To be checked with 

```
snakemake -j1 plot_all_resources
``` 

or

```
snakemake -j1 results/_resources/plots/scal_conv_pp-capacity_net_el.png
```

Thanks!

**Review by Stefanie08 — APPROVED** [review]
Both commands work as expected.
Just as a side note:
There is also a typing error in the legend

grafik

**Comment by MaGering** [comment]
> Both commands work as expected. Just as a side note: There is also a typing error in the legend
> 
> grafik

Thanks @Stefanie08. And for creating issue https://github.com/rl-institut/oemof-B3/issues/348.

**Pull request merged**
